export const courts = [
  {
    id: 1,
    name: "los carpinchos",
    price: "1500-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.8",
    location: "20",
    type: "Futbol",
  },
  {
    id: 2,
    name: "Hockey club",
    price: "1500-2000",
    timeTables: "lunes a domingo (8-20hs)",
    img: require("../../../Images/HockeyCourt.jpg"),
    rating: "4.2",
    location: "5000",
    type: "Hockey",
  },
  {
    id: 3,
    name: "chapelco Golf",
    price: "4000-5000",
    timeTables: "lunes a domingo (9-19hs)",
    img: require("../../../Images/GolfCourt.jpg"),
    rating: "4.2",
    location: "10",
    type: "Golf",
  },
  {
    id: 4,
    name: "tenis club",
    price: "1000-2000",
    timeTables: "lunes a domingo (9-23hs)",
    img: require("../../../Images/TennisCourt.jpg"),
    rating: "3",
    location: "15",
    type: "Tennis",
  },
  {
    id: 5,
    name: "Paddle club",
    price: "1000-2000",
    timeTables: "lunes a domingo (9-23hs)",
    img: require("../../../Images/PaddleCourt.jpg"),
    rating: "4.5",
    location: "15",
    type: "Paddle",
  },
  {
    id: 6,
    name: "la pelota siempre al 10",
    price: "1600-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.2",
    location: "20",
    type: "Futbol",
  },
  {
    id: 7,
    name: "los carpinchos",
    price: "1500-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.8",
    location: "20",
    type: "Futbol",
  },
  {
    id: 8,
    name: "los carpinchos",
    price: "1500-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.8",
    location: "20",
    type: "Futbol",
  },
  {
    id: 9,
    name: "los carpinchos",
    price: "1500-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.8",
    location: "20",
    type: "Futbol",
  },
  {
    id: 10,
    name: "los carpinchos",
    price: "1500-2000",
    timeTables: "lunes a domingo (18-24hs)",
    img: require("../../../Images/FootballCourt.jpg"),
    rating: "4.8",
    location: "20",
    type: "Futbol",
  },
];
